apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trigger-func
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/sglynn11/trigger_func
        env:
        - name: TARGET
          value: "Dia duit ar domhan"
